In [1]:
# Cell 1 — Imports & config

import os
from pathlib import Path
import pandas as pd

PROJECTS_ROOT = Path("/Volumes/LaCie/Astrophotography/Projects")

TIF_EXTENSIONS = {".tif", ".tiff"}

# Directory names that mark calibration/stacking folders — don't descend past these.
STOP_DIR_NAMES = {"bias", "dark", "flat", "light", "stack"}

# Composite filenames to ignore (case-insensitive) — not the object's own final image.
IGNORE_TIF_NAMES = {"nebula.tif", "nebulaf.tif", "galaxies.tif", "galaxiesf.tif", "galaxy.tif", "galaxyf.tif", "stars.tif"}

print(f"Projects root: {PROJECTS_ROOT} (exists: {PROJECTS_ROOT.exists()})")

Projects root: /Volumes/LaCie/Astrophotography/Projects (exists: True)

In [2]:
# Cell 2 — Discovery

def find_candidate_tiffs(object_folder: Path) -> list[Path]:
    """Recursively collect candidate TIFFs under object_folder, pruning calibration/stack subfolders."""
    candidates = []
    for root, dirs, files in os.walk(object_folder):
        dirs[:] = [d for d in dirs if d.lower() not in STOP_DIR_NAMES]
        for filename in files:
            if filename.startswith("."):
                continue  # skip AppleDouble metadata files (e.g. "._m16.tif")
            path = Path(root) / filename
            if path.suffix.lower() not in TIF_EXTENSIONS:
                continue
            if filename.lower() in IGNORE_TIF_NAMES:
                continue
            candidates.append(path)
    return sorted(candidates)


def discover_dso_candidates() -> dict[str, list[Path]]:
    """DSO/<FolderName>/ → objectId = folder name lowercased."""
    result = {}
    dso_root = PROJECTS_ROOT / "DSO"
    if not dso_root.exists():
        print(f"  WARNING: {dso_root} not found")
        return result
    for folder in sorted(dso_root.iterdir()):
        if not folder.is_dir():
            continue
        result[folder.name.lower()] = find_candidate_tiffs(folder)
    return result

In [3]:
# Cell 3 — Run discovery & build review table

candidates = discover_dso_candidates()

rows = []
for object_id, paths in candidates.items():
    if not paths:
        rows.append({"objectId": object_id, "candidate": None, "size_mb": None})
    for path in paths:
        rows.append({
            "objectId": object_id,
            "candidate": str(path.relative_to(PROJECTS_ROOT)),
            "size_mb": round(path.stat().st_size / (1024 * 1024), 1),
        })

candidates_df = pd.DataFrame(rows, columns=["objectId", "candidate", "size_mb"])

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", 100)
candidates_df

       objectId                              candidate  size_mb
0     barnard72            DSO/Barnard72/barnard72.tif     66.8
1        ic1805              DSO/IC1805/c8/IC18052.tif     66.9
2        ic1805           DSO/IC1805/redcat/IC1805.tif    148.6
3         ic410                DSO/IC410/IC410-HOO.tif     62.0
4         ic410                    DSO/IC410/IC410.tif     62.0
5         ic410                 DSO/IC410/tadpoles.tif     66.9
6         ic434                  DSO/IC434/1/IC434.tif     65.1
7         ic434                  DSO/IC434/2/IC434.tif     44.9
8         ic434                  DSO/IC434/3/IC434.tif    117.0
9         ic443                    DSO/IC443/IC443.tif    148.8
10       ic5146                  DSO/IC5146/IC5146.tif     66.5
11      ldn1625                DSO/LDN1625/LDN1625.tif     66.8
12           m1                          DSO/M1/M1.tif     57.8
13         m101                      DSO/M101/M101.tif     66.4
14         m104                      DSO/M104/M104.tif     64.2
15          m13                        DSO/M13/m13.tif     66.8
16          m16          DSO/M16/Processed/M16/m16.tif     64.6
17          m16  DSO/M16/Processed/Pillars/pillars.tif     55.0
18          m17                        DSO/M17/m17.tif     66.2
19          m17     DSO/M17/processed/LExtreme/m17.tif     66.2
20          m17     DSO/M17/processed/LSynergy/m17.tif     66.2
21          m20                        DSO/M20/m20.tif     66.2
22          m27                        DSO/M27/M27.tif     66.5
23           m3                          DSO/M3/m3.tif     66.7
24          m31                        DSO/M31/M31.tif    149.1
25          m33                        DSO/M33/m33.tif     66.0
26          m42                        DSO/M42/m42.tif    147.7
27          m45                        DSO/M45/M45.tif    148.6
28          m51                     DSO/M51/1x/m51.tif     66.0
29          m51                     DSO/M51/2x/m51.tif     66.9
30           m8                          DSO/M8/M8.tif     66.4
31          m81                     DSO/M81/m81m82.tif     66.7
32          m82                        DSO/M82/M82.tif     65.7
33          m83                        DSO/M83/m83.tif     66.4
34          m97                        DSO/M97/m97.tif     63.7
35    markarian            DSO/Markarian/markarian.tif    233.6
36      ngc1499                DSO/NGC1499/NGC1499.tif    147.8
37      ngc1977                DSO/NGC1977/NGC1977.tif     67.3
38      ngc2237                DSO/NGC2237/ngc2237.tif    149.0
39      ngc2264         DSO/NGC2264/NGC2264-signed.tif     26.3
40      ngc2264                DSO/NGC2264/NGC2264.tif     80.4
41      ngc2359                DSO/NGC2359/NGC2359.tif     65.6
42      ngc2362                DSO/NGC2362/NGC2362.tif     66.0
43      ngc2467                DSO/NGC2467/NGC2467.tif     56.4
44       ngc281                  DSO/NGC281/NGC281.tif     66.7
45      ngc3372                DSO/NGC3372/NGC3372.tif     44.8
46      ngc4565                DSO/NGC4565/NGC4565.tif     65.9
47      ngc6888                DSO/NGC6888/NGC6888.tif     66.6
48      ngc6960                DSO/NGC6960/NGC6960.tif     55.9
49      ngc6979                DSO/NGC6979/NGC6979.tif     65.1
50      ngc6992                DSO/NGC6992/NGC6992.tif     66.5
51      ngc7000  DSO/NGC7000/CygnusWall/CygnusWall.tif     66.5
52      ngc7293                DSO/NGC7293/NGC7293.tif     59.4
53      ngc7380                DSO/NGC7380/NGC7380.tif     66.5
54      ngc7635            DSO/NGC7635/NGC7635-HOO.tif    116.1
55   leotriplet          DSO/leotriplet/leotriplet.tif     66.4
56  rhoophiuchi        DSO/rhoophiuchi/rhoophiuchi.tif    145.6
57  whalehockey        DSO/whalehockey/whalehockey.tif     66.8

In [4]:
# Cell 4 — Flag objects with zero or multiple candidates for manual review

counts = candidates_df.groupby("objectId")["candidate"].apply(lambda s: s.notna().sum())
needs_review = counts[counts != 1]
print(f"{len(counts)} DSO objects scanned; {len(needs_review)} need review (0 or multiple candidates):")
needs_review

48 DSO objects scanned; 7 need review (0 or multiple candidates):

objectId
ic1805     2
ic410      3
ic434      3
m16        2
m17        3
m51        2
ngc2264    2
Name: candidate, dtype: int64

In [5]:
# Cell 5 — Output directory

OUTPUT_DIR = Path("/Users/jwatts/Documents/astrophotography/Backup")  # set this to a local folder on the laptop before running

if not str(OUTPUT_DIR):
    raise ValueError("Set OUTPUT_DIR to a local folder path before running this cell")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
print(f"Output dir: {OUTPUT_DIR}")

Output dir: /Users/jwatts/Documents/astrophotography/Backup

In [6]:
# Cell 6 — Copy candidates to OUTPUT_DIR

import shutil

def dest_filename(object_id: str, path: Path, object_folder: Path, num_candidates: int) -> str:
    ext = path.suffix.lower()
    if num_candidates == 1:
        return f"{object_id}{ext}"
    subdir_parts = path.relative_to(object_folder).parts[:-1]
    suffix = "-".join(subdir_parts) if subdir_parts else path.stem
    return f"{object_id}-{suffix}{ext}"

copied = []
for object_id, paths in candidates.items():
    if not paths:
        continue
    object_folder = PROJECTS_ROOT / "DSO" / object_id
    # folder names on disk may not be lowercase; find the actual folder to compute relative paths
    for folder in (PROJECTS_ROOT / "DSO").iterdir():
        if folder.is_dir() and folder.name.lower() == object_id:
            object_folder = folder
            break
    for path in paths:
        dest = OUTPUT_DIR / dest_filename(object_id, path, object_folder, len(paths))
        shutil.copy2(path, dest)
        copied.append({"objectId": object_id, "source": str(path.relative_to(PROJECTS_ROOT)), "dest": dest.name})

print(f"Copied {len(copied)} files to {OUTPUT_DIR}")
pd.DataFrame(copied, columns=["objectId", "source", "dest"])

Copied 58 files to /Users/jwatts/Documents/astrophotography/Backup

,objectId,source,dest
0,barnard72,DSO/Barnard72/barnard72.tif,barnard72.tif
1,ic1805,DSO/IC1805/c8/IC18052.tif,ic1805-c8.tif
2,ic1805,DSO/IC1805/redcat/IC1805.tif,ic1805-redcat.tif
3,ic410,DSO/IC410/IC410-HOO.tif,ic410-IC410-HOO.tif
4,ic410,DSO/IC410/IC410.tif,ic410-IC410.tif
5,ic410,DSO/IC410/tadpoles.tif,ic410-tadpoles.tif
6,ic434,DSO/IC434/1/IC434.tif,ic434-1.tif
7,ic434,DSO/IC434/2/IC434.tif,ic434-2.tif
8,ic434,DSO/IC434/3/IC434.tif,ic434-3.tif
9,ic443,DSO/IC443/IC443.tif,ic443.tif
10,ic5146,DSO/IC5146/IC5146.tif,ic5146.tif
11,ldn1625,DSO/LDN1625/LDN1625.tif,ldn1625.tif
12,m1,DSO/M1/M1.tif,m1.tif
13,m101,DSO/M101/M101.tif,m101.tif
14,m104,DSO/M104/M104.tif,m104.tif
15,m13,DSO/M13/m13.tif,m13.tif
16,m16,DSO/M16/Processed/M16/m16.tif,m16-Processed-M16.tif
17,m16,DSO/M16/Processed/Pillars/pillars.tif,m16-Processed-Pillars.tif
18,m17,DSO/M17/m17.tif,m17-m17.tif
19,m17,DSO/M17/processed/LExtreme/m17.tif,m17-processed-LExtreme.tif
20,m17,DSO/M17/processed/LSynergy/m17.tif,m17-processed-LSynergy.tif
21,m20,DSO/M20/m20.tif,m20.tif
22,m27,DSO/M27/M27.tif,m27.tif
23,m3,DSO/M3/m3.tif,m3.tif
24,m31,DSO/M31/M31.tif,m31.tif
25,m33,DSO/M33/m33.tif,m33.tif
26,m42,DSO/M42/m42.tif,m42.tif
27,m45,DSO/M45/M45.tif,m45.tif
28,m51,DSO/M51/1x/m51.tif,m51-1x.tif
29,m51,DSO/M51/2x/m51.tif,m51-2x.tif
30,m8,DSO/M8/M8.tif,m8.tif
31,m81,DSO/M81/m81m82.tif,m81.tif
32,m82,DSO/M82/M82.tif,m82.tif
33,m83,DSO/M83/m83.tif,m83.tif
34,m97,DSO/M97/m97.tif,m97.tif
35,markarian,DSO/Markarian/markarian.tif,markarian.tif
36,ngc1499,DSO/NGC1499/NGC1499.tif,ngc1499.tif
37,ngc1977,DSO/NGC1977/NGC1977.tif,ngc1977.tif
38,ngc2237,DSO/NGC2237/ngc2237.tif,ngc2237.tif
39,ngc2264,DSO/NGC2264/NGC2264-signed.tif,ngc2264-NGC2264-signed.tif
40,ngc2264,DSO/NGC2264/NGC2264.tif,ngc2264-NGC2264.tif
41,ngc2359,DSO/NGC2359/NGC2359.tif,ngc2359.tif
42,ngc2362,DSO/NGC2362/NGC2362.tif,ngc2362.tif
43,ngc2467,DSO/NGC2467/NGC2467.tif,ngc2467.tif
44,ngc281,DSO/NGC281/NGC281.tif,ngc281.tif
45,ngc3372,DSO/NGC3372/NGC3372.tif,ngc3372.tif
46,ngc4565,DSO/NGC4565/NGC4565.tif,ngc4565.tif
47,ngc6888,DSO/NGC6888/NGC6888.tif,ngc6888.tif
48,ngc6960,DSO/NGC6960/NGC6960.tif,ngc6960.tif
49,ngc6979,DSO/NGC6979/NGC6979.tif,ngc6979.tif
50,ngc6992,DSO/NGC6992/NGC6992.tif,ngc6992.tif
51,ngc7000,DSO/NGC7000/CygnusWall/CygnusWall.tif,ngc7000.tif
52,ngc7293,DSO/NGC7293/NGC7293.tif,ngc7293.tif
53,ngc7380,DSO/NGC7380/NGC7380.tif,ngc7380.tif
54,ngc7635,DSO/NGC7635/NGC7635-HOO.tif,ngc7635.tif
55,leotriplet,DSO/leotriplet/leotriplet.tif,leotriplet.tif
56,rhoophiuchi,DSO/rhoophiuchi/rhoophiuchi.tif,rhoophiuchi.tif
57,whalehockey,DSO/whalehockey/whalehockey.tif,whalehockey.tif